export default {
    AUTH_IS_AUTHENTICATED: 'AUTH_IS_AUTHENTICATED',
    AUTH_ROLE_IS_WORKSHOP: 'AUTH_ROLE_IS_WORKSHOP',
    AUTH_ROLE_IS_USER: 'AUTH_ROLE_IS_USER',
    AUTH_ROLE_IS_ADMIN: 'AUTH_ROLE_IS_ADMIN',
    AUTH_ROLE_IS_GUEST: 'AUTH_ROLE_IS_GUEST',
    IS_ROLES_LOADED: 'IS_ROLES_LOADED',
    IS_OFFER_CLOSED: 'IS_OFFER_CLOSED',
    AUTH_ROLE_IS_MODERATOR: 'AUTH_ROLE_IS_MODERATOR'
}
