export default {
    AUTH_SET_TOKEN: 'AUTH_SET_TOKEN',
    AUTH_UNSET_TOKEN: 'AUTH_UNSET_TOKEN',
    AUTH_SET_ROLES: 'AUTH_SET_ROLES',

    MAIN_SAVE_CAR_MAKES: 'MAIN_SAVE_CAR_MAKES',
    MAIN_SAVE_SERVICES: 'MAIN_SAVE_SERVICES',

    REVIEWS_SAVE: 'REVIEWS_SAVE',
    REVIEWS_SAVE_FOR_WORKSHOP: 'REVIEWS_SAVE_FOR_WORKSHOP',

    BLOG_SAVE_LATEST: 'BLOG_SAVE_LATEST',
    BLOG_SAVE: 'BLOG_SAVE',
    BLOG_SAVE_RELATIVE: 'BLOG_SAVE_RELATIVE',

    WORKSHOP_SAVE_WORKSHOPS: 'WORKSHOP_SAVE_SHORTCUTS',
    WORKSHOP_SAVE: 'WORKSHOP_SAVE',

    REPAIR_REQUESTS_SAVE: 'REPAIR_REQUESTS_SAVE',
    REPAIR_REQUEST_WORKSHOP_OFFERS_SAVE: 'REPAIR_REQUEST_WORKSHOP_OFFERS_SAVE',
    REPAIR_REQUEST_USER_REQUESTS_SAVE: 'REPAIR_REQUEST_USER_REQUESTS_SAVE',

    WORKSHOP_SETTINGS_SAVE_BASIC: 'WORKSHOP_SETTINGS_SAVE_BASIC',
    WORKSHOP_SERVICES_SAVE_MAIN: 'WORKSHOP_SERVICES_SAVE_MAIN',
    WORKSHOP_SERVICES_SAVE_ADDITIONAL: 'WORKSHOP_SERVICES_SAVE_ADDITIONAL',
    WORKSHOP_PAYMENT_OPTIONS_SAVE: 'WORKSHOP_PAYMENT_OPTIONS_SAVE',
    WORKSHOP_MAKES_SAVE: 'WORKSHOP_MAKES_SAVE',
    WORKSHOP_SPARE_PARTS_SAVE: 'WORKSHOP_SPARE_PARTS_SAVE',
    WORKSHOP_SCHEDULE_SAVE: 'WORKSHOP_SCHEDULE_SAVE',
    WORKSHOP_WARRANTY_SAVE: 'WORKSHOP_WARRANTY_SAVE',
    WORKSHOP_SAVE_LOGO_LINK: 'WORKSHOP_SAVE_LOGO_LINK',
    WORKSHOP_SAVE_CERTIFICATES: 'WORKSHOP_SAVE_CERTIFICATES',
    WORKSHOP_EMAIL_SAVE: 'WORKSHOP_EMAIL_SAVE',

    ERROR_SET_STATUS: 'ERROR_SET_STATUS',
    ERROR_SET_MESSAGE: 'ERROR_SET_MESSAGE',

    REPAIR_REQUEST_SAVE: 'REPAIR_REQUEST_SAVE',
    REPAIR_REQUEST_SAVE_MAKES: 'REPAIR_REQUEST_FETCH_MAKES',
    REPAIR_REQUEST_SAVE_SERVICES: 'REPAIR_REQUEST_FETCH_SERVICES',
    REPAIR_REQUEST_SAVE_SPARE_PARTS: 'REPAIR_REQUEST_FETCH_SPARE_PARTS',
    REPAIR_REQUEST_SAVE_OFFERED_WORKSHOPS: 'WORKSHOP_SAVE_OFFERED',
    REPAIR_REQUEST_SAVE_APPLIED_WORKSHOP: 'REPAIR_REQUEST_SAVE_APPLIED_WORKSHOP',

    PAGINATION_METADATA_SAVE: 'PAGINATION_METADATA_SAVE',
    FILTERS_SAVE_MAKES: 'FILTERS_SAVE_MAKES',
    FILTERS_SAVE_CITIES: 'FILTERS_SAVE_CITIES',
    ENABLE_SEARCH_WIDGET: 'ENABLE_SEARCH_WIDGET',
    AUTH_UNSET_ROLES: 'AUTH_UNSET_ROLES'

}
