<?php

use Illuminate\Database\Seeder;
use App\ShopBrand;

class ShopMakeTableSeeder extends Seeder
{
    public function run()
    {
        $makesData = [
            ['name' => 'Acura'],
            ['name' => 'Alfa Romeo'],
            ['name' => 'Aston Martin'],
            ['name' => 'Audi'],
            ['name' => 'Bentley'],
            ['name' => 'BMW'],
            ['name' => 'Brilliance'],
            ['name' => 'Buick'],
            ['name' => 'BYD'],
            ['name' => 'Cadillac'],
            ['name' => 'Changan'],
            ['name' => 'Chery'],
            ['name' => 'Chevrolet'],
            ['name' => 'Chrysler'],
            ['name' => 'Citroen'],
            ['name' => 'Dadi'],
            ['name' => 'Daewoo'],
            ['name' => 'Daihatsu'],
            ['name' => 'Derways'],
            ['name' => 'Dodge'],
            ['name' => 'FAW'],
            ['name' => 'Ferrari'],
            ['name' => 'Fiat'],
            ['name' => 'Ford'],
            ['name' => 'Geely'],
            ['name' => 'GMC'],
            ['name' => 'Great Wall'],
            ['name' => 'Haima'],
            ['name' => 'Honda'],
            ['name' => 'Hummer'],
            ['name' => 'Hyundai'],
            ['name' => 'Infiniti'],
            ['name' => 'Isuzu'],
            ['name' => 'Iveco'],
            ['name' => 'Jaguar'],
            ['name' => 'Jeep'],
            ['name' => 'Jiangling'],
            ['name' => 'JMC'],
            ['name' => 'Kia'],
            ['name' => 'Lamborghini'],
            ['name' => 'Lancia'],
            ['name' => 'Land Rover'],
            ['name' => 'Landwind'],
            ['name' => 'Lexus'],
            ['name' => 'Lifan'],
            ['name' => 'Lincoln'],
            ['name' => 'Lotus'],
            ['name' => 'Maserati'],
            ['name' => 'Maybach'],
            ['name' => 'Mazda'],
            ['name' => 'Mercedes'],
            ['name' => 'Mercury'],
            ['name' => 'MG'],
            ['name' => 'Mini'],
            ['name' => 'Mitsubishi'],
            ['name' => 'Mosler'],
            ['name' => 'Nissan'],
            ['name' => 'Oldsmobile'],
            ['name' => 'Opel'],
            ['name' => 'Panoz'],
            ['name' => 'Peugeot'],
            ['name' => 'Plymouth'],
            ['name' => 'Pontiac'],
            ['name' => 'Porsche'],
            ['name' => 'Ram'],
            ['name' => 'Renault'],
            ['name' => 'Rolls Royce'],
            ['name' => 'Rover'],
            ['name' => 'Saab'],
            ['name' => 'Saleen'],
            ['name' => 'Saturn'],
            ['name' => 'Scion'],
            ['name' => 'Seat'],
            ['name' => 'Skoda'],
            ['name' => 'Smart'],
            ['name' => 'Ssang Yong'],
            ['name' => 'Subaru'],
            ['name' => 'Suzuki'],
            ['name' => 'Toyota'],
            ['name' => 'Volkswagen'],
            ['name' => 'Volvo'],
            ['name' => 'Xin Kai'],
            ['name' => 'ZAZ'],
            ['name' => 'ZX'],
            ['name' => 'ВАЗ'],
            ['name' => 'ТаГАЗ'],
            ['name' => 'УАЗ'],
        ];

        foreach ($makesData as $makeData) {
            ShopBrand::create($makeData);
        }
    }
}
