export default {
    ADMIN_PANEL_ENABLE: 'ADMIN_PANEL_ENABLE',
    ADMIN_PANEL_DISABLE: 'ADMIN_PANEL_DISABLE',

    FETCH_ADMIN_USERS: 'FETCH_ADMIN_USERS',
    CREATE_ADMIN_USER: 'CREATE_ADMIN_USER',
    FETCH_ADMIN_USER: 'FETCH_ADMIN_USER',
    UPDATE_ADMIN_USER: 'UPDATE_ADMIN_USER',
    DELETE_ADMIN_USER: 'DELETE_ADMIN_USER',

    FETCH_CUSTOMER_USERS: 'FETCH_CUSTOMER_USERS',
    CREATE_CUSTOMER_USER: 'CREATE_CUSTOMER_USER',
    FETCH_CUSTOMER_USER: 'FETCH_CUSTOMER_USER',
    UPDATE_CUSTOMER_USER: 'UPDATE_CUSTOMER_USER',
    DELETE_CUSTOMER_USER: 'DELETE_CUSTOMER_USER',

    FETCH_REPAIR_REQUESTS: 'FETCH_REPAIR_REQUESTS',
    FETCH_REPAIR_REQUEST: 'FETCH_REPAIR_REQUEST',
    DELETE_REPAIR_REQUEST: 'DELETE_CUSTOMER_USER',
    DELETE_REPAIR_REQUEST_OFFER: 'DELETE_REPAIR_REQUEST_OFFER',
    FETCH_REPAIR_REQUEST_OFFERS: 'FETCH_REPAIR_REQUEST_OFFERS',

    FETCH_SHOPS: 'FETCH_SHOPS',
    FETCH_SHOP: 'FETCH_SHOP',
    FETCH_SHOP_REVIEWS: 'FETCH_SHOP_REVIEWS',
    UPDATE_SHOP: 'UPDATE_SHOP',
    DELETE_SHOP: 'DELETE_SHOP'
}
