export default {
    ADMIN_PANEL_DISABLE: 'ADMIN_PANEL_DISABLE',
    ADMIN_PANEL_ENABLE: 'ADMIN_PANEL_ENABLE',

    SAVE_ADMIN_USERS: 'SAVE_ADMIN_USERS',
    SAVE_ADMIN_CURRENT_USER: 'SAVE_ADMIN_CURRENT_USER',

    SAVE_CUSTOMER_USERS: 'SAVE_CUSTOMER_USERS',
    SAVE_CUSTOMER_CURRENT_USER: 'SAVE_CUSTOMER_CURRENT_USER',

    SAVE_REPAIR_REQUESTS: 'SAVE_REPAIR_REQUESTS',
    SAVE_REPAIR_REQUESTS_CURRENT: 'SAVE_REPAIR_REQUESTS_CURRENT',
    SAVE_REPAIR_REQUESTS_OFFERS: 'SAVE_REPAIR_REQUESTS_OFFERS',

    SAVE_SHOPS: 'SAVE_SHOPS',
    SAVE_CURRENT_SHOP: 'SAVE_CURRENT_SHOP',
    SAVE_SHOP_REVIEWS: 'SAVE_SHOP_REVIEWS',

    ENABLE_SEARCH_WIDGET: 'ENABLE_SEARCH_WIDGET'
}
